#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

killall xembedsniproxy
# Launch bar
polybar main -r &

killall xembedsniproxy
